### ISSUE TITLE
Typos in the guide

### ISSUE THREAD

**Issue by nicoleCamoro** [accordproject/template-studio-v2#102]
I found a typo when cloning my fork since I got an error. I would like to fix this and try to check for other typos and grammatical errors.

**Comment by aditya1rawat** [comment]
@irmerk Which directory is the guide with the typos in?

**Comment by jolanglinais** [comment]
@aditya1rawat: I believe @nicoleCamoro already corrected them in #103 

Closing unless @nicoleCamoro wants to reopen.

**Comment by aditya1rawat** [comment]
Oh ok, no problem
