### ISSUE TITLE
Remove github banner, replace with link in nav bar

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/template-studio-v2#106]
Template Studio currently has a github banner than looks out of place and overlaps important elements of the UI, in addition to creating challenges in having to design around the banner for Template Studio in addition to making the components it overlaps extensible to websites that don't have the banner.

![image](https://user-images.githubusercontent.com/40569793/66418466-2bdec580-e9d0-11e9-9360-010f6a423ede.png)

Remove the banner and replace with a hyperlink with the github logo next to it in the top nav bar.

The link and github logo should turn rgb(25, 198, 199) on hover.

![image](https://user-images.githubusercontent.com/40569793/66418664-909a2000-e9d0-11e9-8ec6-6be9430f3c45.png)

**Comment by ErnstGotera** [comment]
Can I try to solve this at @Novahelm ?

**Comment by julianasinai** [comment]
Can I work on it?

**Comment by Michael-Grover** [comment]
@Emizel sure, thank you.

Sorry @julianasinai , it looks like @Emizel claimed the issue a little bit before you, so @Emizel can have first crack at it.

**Comment by ErnstGotera** [comment]
I eliminated the Github banner and added the link as requested. Just some questions to finish and make the pull request, how you would prefer me to add the Github logo, with an svg, img or font icon? And how should I include it? Also, how can I apply the css in the project? Is there a css file I should use or create, or should include it in the styled components of the header section?

**Comment by Michael-Grover** [comment]
@Emizel, on whether to use svg, img, or font icon: do whatever you think is best. Let me know if you need any image assets.

@DianaLease could probably provide a more detailed answer to this and your other questions

**Comment by DianaLease** [comment]
Hi @Emizel! Thanks for taking this on!

For the github logo, a png file would probably be best. You can include it in the `public/img` directory, and import it into the component similarly to how the logo is being imported in `src/containers/Header/index.js`. 

For styling, please use a styled component in the Header component. More info on styled components can be found in their docs: https://www.styled-components.com/docs There are also plenty examples throughout the codebase for reference.

**Comment by ujjawaljaiswal2017** [comment]
Is this issue still open for contribution?

**Comment by jolanglinais** [comment]
@ujjawaljaiswal2017: It is currently being fixed in #108

**Comment by jolanglinais** [comment]
Opening back up as stale. Future contributors reference #108 before starting.

**Comment by jolanglinais** [comment]
Finished in #157
