### ISSUE TITLE
Clause Template Persists on State when Deleted

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#111]
**Describe the bug**
The clause template persists in `clauseTemplatesState` when deleted from the contract

**To Reproduce**
1. Run locally with `cicero-ui` linked through `npm link`
2. Add a clause template to the contract
3. Select the delete icon on the clause template, this will remove it
4. Open the console and view the latest redux state
5. Notice that `clauseTemplatesState` still contains the template

**Expected behavior**
Deletion of the clause template should also remove it from the `clauseTemplatesState` part of the redux store

**Screenshots**
<img width="1680" alt="Screen Shot 2019-10-17 at 11 52 14 AM" src="https://user-images.githubusercontent.com/36460856/67025899-cc21a200-f0d4-11e9-8d99-18ac8d5ba548.png">

**Additional context**
Related issue: #112

**Comment by Andre-rsfc** [comment]
I will work on it

**Comment by Andre-rsfc** [comment]
Hey @irmerk where is the delete icon?

**Comment by jolanglinais** [comment]
@Andre-rsfc when you hover over the clause template it should show.

**Comment by Andre-rsfc** [comment]
@irmerk I can't reproduce :(

**Comment by jolanglinais** [comment]
Go to https://accordproject-studio.netlify.com/
Select `+ Add to contract` under "Acceptance of Delivery" on the right.
Hover over the clause template
You'll see the delete icon in the top right of the clause template

**Comment by Andre-rsfc** [comment]
Understand, thansk :smile:

**Comment by jolanglinais** [comment]
Opening back up as stale.
