### ISSUE TITLE
Clause Error Persists in Logger when Deleted

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#112]
**Describe the bug**
The clause error persists in the `ErrorLogger` component when deleted from the contract

**To Reproduce**
1. Run locally with `cicero-ui` linked through `npm link`
2. Add a clause template to the contract
3. Type a random letter into the clause, causing a parse error
4. Select the delete icon on the clause template, this will remove it
5. Notice that the error in the ErrorLogger still contains the parse error

**Expected behavior**
Deletion of the clause template should also remove its corresponding errors from the redux store

**Screenshots**
<img width="1680" alt="Screen Shot 2019-10-17 at 11 52 14 AM" src="https://user-images.githubusercontent.com/36460856/67025899-cc21a200-f0d4-11e9-8d99-18ac8d5ba548.png">

**Additional context**
Related issue: #111

**Comment by Andre-rsfc** [comment]
I will work on it

**Comment by jolanglinais** [comment]
@Andre-rsfc any progress on this? Opening back up in the meantime.

**Comment by ardelapaz** [comment]
I would like to work on this as my first issue, however, I can't seem to find this specific issue. Upon deleting the contract, the error in the error logger at the bottom is removed and nothing is in the store. Am I looking in the right area for the error in the store? (Contract state -> clauses -> clauseId -> parseError)

I am, however, able to get a parse error by adding a contract, adding any character to the contract, adding a character below the contract, and upon adding a second character inside the contract the parse error for the original character in the contract appears. This was the only way I could get a parse error to show up on my end.

**Comment by jolanglinais** [comment]
> I would like to work on this as my first issue, however, I can't seem to find this specific issue. Upon deleting the contract, the error in the error logger at the bottom is removed and nothing is in the store. Am I looking in the right area for the error in the store? (Contract state -> clauses -> clauseId -> parseError)

I think this more refers to `clauseTemplateState`, where the template (which is used to parse the clause against to determine if there is an error) remains on state when the clause is deleted.

> I am, however, able to get a parse error by adding a contract, adding any character to the contract, adding a character below the contract, and upon adding a second character inside the contract the parse error for the original character in the contract appears. This was the only way I could get a parse error to show up on my end.

This seems weird. So adding a clause and adding a character within the clause (not between quotation marks / inside variables) does not cause a parse error? You have to do this, then type outside the clause, then type in the clause again?

**Comment by ardelapaz** [comment]
I went back and did some more testing, and the outcome is I'm able to replicate the error multiple ways now.

I have replicated it your way just a small handful of times, but the majority of the time is either the way I described earlier, or this: https://www.loom.com/share/27692afecb7b42e1acb152d82d751596

Recently, I haven't needed to type a third character for the error to throw, just the two characters as the video above shows.

Regardless I assume whatever is making this alternate is a completely separate issue and isn't related to the original issue of clearing the state? If that's the case, will clearing clauseTemplatesState upon deleting the template be the desired solution?

**Comment by jolanglinais** [comment]
Yeah I believe this is a different issue. Quite bizarre, I've never seen this happen.

I think clearing the `clauseTemplateState` is the desired solution for this issue. I may be mistaken, but I believe this is added to the state only as a means to parse the clause. So if the clause is removed, the template is now dead weight and cannot be used if the same clause is added again - it is added with a `uuid`.

**Comment by ardelapaz** [comment]
Clearing clauseTemplateState on deletion sounds like something I'd like to take a crack at. I'll update you as soon as I make some progress!

**Comment by DianaLease** [comment]
> Yeah I believe this is a different issue. Quite bizarre, I've never seen this happen.

I have also not seen the issue where the parse error does not show up until you type outside the clause. Can you open that as a new issue please @ardelapaz with the browser you are using?

> I think clearing the `clauseTemplateState` is the desired solution for this issue. I may be mistaken, but I believe this is added to the state only as a means to parse the clause. So if the clause is removed, the template is now dead weight and cannot be used if the same clause is added again - it is added with a `uuid`.

Yes, that sounds correct to me!

**Comment by ardelapaz** [comment]
I've found that my main obstacle when trying to clear the clauseTemplatesState is obtaining the clauseTemplateRef from the clause that's being deleted, and passing that into a reducer to be able to remove that ID from the clauseTemplatesState. One workaround I found was to just set the clauseId as the key of each clauseTemplatesState item when added, since the clauseId easily accessible, but I'd rather not use that approach as it stores items in the clauseTemplatesState under the clauseId instead of it's own Id.

Is there a built in way that I'm not seeing to obtain the clauseTemplateRef (clauseTemplatesState item id or key) upon deletion of the clause?

**Comment by jolanglinais** [comment]
I don't think so. I would be following how the clause template is added to the store when you add a clause, and try to replicate a similar behavior when deleting the clause to also delete its corresponding template reference.

**Comment by dselman** [comment]
> Yeah I believe this is a different issue. Quite bizarre, I've never seen this happen.
> 
> I think clearing the `clauseTemplateState` is the desired solution for this issue. I may be mistaken, but I believe this is added to the state only as a means to parse the clause. So if the clause is removed, the template is now dead weight and cannot be used if the same clause is added again - it is added with a `

We need to be careful here. You can have multiple instances (clauses) for the same template. Templates should be identified by their id. Clauses have an id assigned on creation, and you can get the id of their template.

**Comment by DianaLease** [comment]
> We need to be careful here. You can have multiple instances (clauses) for the same template. Templates should be identified by their id. Clauses have an id assigned on creation, and you can get the id of their template.

@dselman, that is a good point. Additionally, even if all of the clauses using that template have been removed, the user may still wish to edit the template for later use? May need some UX input from @Michael-Grover on this one.

**Comment by ardelapaz** [comment]
> Templates should be identified by their id. Clauses have an id assigned on creation, and you can get the id of their template.

The issue that I was running into was being able to access that template's ID. The template's ID is only stored in the store under contractState -> clauses -> clasueTemplateRef but upon deletion of a clausetemplate the only thing that is passed through is the clauseId. See `removeFromContract` in `contractSaga.js` to see what I mean. 

> You can have multiple instances (clauses) for the same template.

I'm still not very comfortable with the project's flow, so I still don't fully understand what clauses you might have under the same template, but with my testing you can add multiple clauses and deleting a template on the contract resulted in deleting the correct clauseTemplatesState item from the state.

Also, none of the clause templates are loading in for me anymore. A recent commit or so must've changed something and isn't working as the netlify version is. It was working just last night before I sent the pull request, but after coming home from work today all I see is this:

![missing](https://user-images.githubusercontent.com/26800229/68055735-be207380-fcc7-11e9-8afd-e245ca1e761f.png)

**Comment by DianaLease** [comment]
hi @ardelapaz , update your branch with the latest master to get the templates to load. this was fixed in the lastest PR.

**Comment by ardelapaz** [comment]
Fixed @DianaLease Thank you,

> You can have multiple instances (clauses) for the same template.

This I don't fully understand. From what I understand, you can add templates from the right side, and the deletion button removes that template. What is meant by "Multiple clauses for the same template"? Isn't the point to delete the deleted clause template from the clauseTemplatesState upon deletion? I guess you could say I'm having trouble understanding what is a clause and what is a clauseTemplate.

**Comment by ardelapaz** [comment]
Also just noticing, this delete functionality; isn't this issue #111 rather than #112 ? There isn't an error in clauseTempaltesState, only the templates themselves. So #112 and #111 are essentially asking for the same solution if I'm not mistaken?

**Comment by dselman** [comment]
> Fixed @DianaLease Thank you,
> 
> > You can have multiple instances (clauses) for the same template.
> 
> This I don't fully understand. From what I understand, you can add templates from the right side, and the deletion button removes that template. What is meant by "Multiple clauses for the same template"? Isn't the point to delete the deleted clause template from the clauseTemplatesState upon deletion? I guess you could say I'm having trouble understanding what is a clause and what is a clauseTemplate.

Please ensure that this works when you have multiple instances of the same clause added to a contract. Eg try adding 3 instances of acceptance-of-delivery. We want different errors for each, and deleting one of the clauses should not impact the errors for the others.

**Comment by ardelapaz** [comment]
Added 3 instances of acceptance-of-delivery, caused a parse error in the middle (2nd) acceptance-of-delivery, and then deleted it. Clause with the error in contractState is removed from contractState in `REMOVE_CLAUSE_FROM_CONTRACT` and the corresponding clause template is removed from clauseTemplatesState upon deletion. 

Adding multiple instances of the same template isn't a problem since each time a new clause is added, it gets a unique id. All I did was add the clause's id to the template item's state to ensure that the template deleted from the store has the clauseId that was just deleted. Since deleting a clause only passes the clauseId and not the template in which it lies, there was no other way to do it.

If this is the desired implementation I can recreate a pull request since I had to remake it due to the master branch update.
![instances](https://user-images.githubusercontent.com/26800229/68061226-355f0300-fcda-11e9-9684-a5aaf1d8ed46.png)

**Comment by ardelapaz** [comment]
@irmerk @DianaLease What I wrote allows for multiple templates to be deleted correctly, even if they're the same template, which was the concern that closed the PR if I'm not mistaken? I'd like to know if I should open another PR or update something before continuing!

**Comment by jolanglinais** [comment]
Based on https://github.com/accordproject/template-studio-v2/pull/144#issuecomment-550488134 from @Michael-Grover, I think #144 is the correct approach.
