### ISSUE TITLE
Navigation to Heading Error

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#113]
**Describe the bug**
When navigating to a normal (non clause template) heading in the Navigation component, a console error occurs

**To Reproduce**
1. Run locally with `cicero-ui` linked through `npm link`
2. Create line breaks greater than the screen height and make a heading
3. Note the heading appears on the left Navigation
4. Select the heading to navigate to it
5. Open the console and view the latest redux state
6. Notice the error 

**Expected behavior**
A smooth scroll effect, similar to what happens when navigating to a clause template through the Navigation sidebar

**Screenshots**
<img width="666" alt="Screen Shot 2019-10-17 at 2 03 14 PM" src="https://user-images.githubusercontent.com/36460856/67035093-f2e8d400-f0e6-11e9-9df0-b48173e2e6ed.png">

```bash
navigateClause.js:65 Uncaught TypeError: overflowY.includes is not a function
    at getScrollParent (navigateClause.js:65)
    at scrollToClause (navigateClause.js:102)
    at navigateToHeader (navigateClause.js:133)
    at onClick (generators.js:52)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:270)
    at executeDispatch (react-dom.development.js:561)
    at executeDispatchesInOrder (react-dom.development.js:583)
```

**Additional context**
This seems to relate to additions made in #104
Related to Issue #113

**Comment by jolanglinais** [comment]
Mentioning @archhhh just as a heads up.

**Comment by archhhh** [comment]
Will try to fix it asap.

**Comment by archhhh** [comment]
Managed to fix this bug. Noticed that heading tags do not have "data-key" in their attributes. In browser manually adding  data-key attribute with appropriate key to the tag via development tools fixes the problem. This problem stems from @accordproject/markdown-editor, in particular SlateAsInputEditor component.

**Comment by jolanglinais** [comment]
@archhhh interesting. Would you want to create that issue in `markdown-editor` and/or work on it there?

**Comment by archhhh** [comment]
i think , this issue can now be closed?
