### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/template-studio-v2#116]
Template Studio is a complex sandbox, so we are adding a welcome screen to introduce users to it and to serve as a starting point. Users can choose to create a new clause template, contract template, start from an existing template, or learn more about how template studio works. 

This welcome screen will appear any time a user opens up template studio. It may be expanded in the future to allow features such as allowing users to upload template from their computer to the template studio.

Implement this welcome screen design. Click the invision link and choose "inspect mode" </> on the bottom to see CSS properties for the elements.
https://invis.io/9GRP1QB8D2U#/389437982_Welcome_1
![image](https://user-images.githubusercontent.com/40569793/67123727-239c3c80-f1bf-11e9-9a4f-b3810be8f598.png)

Let me know if I can help further with design handoff.

Feedback on the design and wording is welcome.

**Comment by Michael-Grover** [comment]
You may need to request access to use the inspect tool on invision. let me know if you need access.

**Comment by archhhh** [comment]
is it related to [issue #5](https://github.com/accordproject/template-studio-v2/issues/5)?

**Comment by jolanglinais** [comment]
@archhhh Yes, whoops, this was an oversight sorry! I'll assign you to this one and close the old one.

**Comment by archhhh** [comment]
@Michael-Grover could you give me access?

**Comment by Michael-Grover** [comment]
@archhhh you should have access now
