### ISSUE TITLE
Right pane content padding

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/template-studio-v2#124]
**Describe the bug**
Currently the content of the right pane has no padding/margin to its left, making it awkwardly abut the the scrollbar.

![image](https://user-images.githubusercontent.com/40569793/67426680-9aaf4780-f5a8-11e9-8a00-776b7181e9d2.png)
![image](https://user-images.githubusercontent.com/40569793/67426650-89663b00-f5a8-11e9-9d13-719869b9ae30.png)

contrast this with how the component looks in Clause, a product who uses this Cicero UI component also. In Clause there is padding on both sides.
![image](https://user-images.githubusercontent.com/40569793/67426855-f1b51c80-f5a8-11e9-90d1-e52785a8ebde.png)

Currently the right side has 10px padding. Set the padding on the right and left to **15px**.

**Comment by nik72619c** [comment]
I'll give it a try

**Comment by nik72619c** [comment]
![tlwrapper](https://user-images.githubusercontent.com/30630904/67616411-e99dec80-f7f5-11e9-8799-659242dee427.png)
I guess ihe padding to TLWrappper that has to be chenged. Am I thinking in the right direction ? Shall I add the required paddings here ?

**Comment by nik72619c** [comment]
#131 @Michael-Grover please have a look :)

**Comment by sachdeva-shrey** [comment]
@Michael-Grover Please close this issue too. Thanks!
