### ISSUE TITLE
Change color of "Add to contract" text to #7B8FAD to match "details" button

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/template-studio-v2#135]
Change the color of the "add to contract" text to match the color of the adjacent "details" button. They are currently different colors.

![image](https://user-images.githubusercontent.com/40569793/67689957-7c639600-f972-11e9-86d3-73c6347f19ce.png)

**Comment by Tamtnguye** [comment]
first time doing a pull request. How do i locate the file to make the changes? like i see different folders but unsure where it is

**Comment by jolanglinais** [comment]
I think this will stem from this file: https://github.com/accordproject/template-studio-v2/blob/master/src/containers/App/themeConstants.js

**Comment by elit-altum** [comment]
@irmerk Is this still open ? Can I work on this ?

**Comment by elit-altum** [comment]
@Michael-Grover Did you mean something like this ?

![image](https://user-images.githubusercontent.com/41413622/75370095-9a261500-58ea-11ea-9f84-79ddc31e1f5d.png)

**Comment by Michael-Grover** [comment]
@elit-altum yes, however the color of the line does not need to be green. It can stay the same gray color as it was. 
![image](https://user-images.githubusercontent.com/40569793/75371054-18a39800-5894-11ea-811a-94f0f73bc774.png)
![image](https://user-images.githubusercontent.com/40569793/75371038-14777a80-5894-11ea-9511-4f62fe92d7df.png)

**Comment by elit-altum** [comment]
> 
> 
> @elit-altum yes, however the color of the line does not need to be green. It can stay the same gray color as it was.
> ![image](https://user-images.githubusercontent.com/40569793/75371054-18a39800-5894-11ea-811a-94f0f73bc774.png)
> ![image](https://user-images.githubusercontent.com/40569793/75371038-14777a80-5894-11ea-9511-4f62fe92d7df.png)

Yes @Michael-Grover I saw that. This is due to the fact that the same theme variable governing the color of the border controls the color of the text. Should I change it ? As it will require changes in the workflow from the pre-defined theme.

**Comment by Michael-Grover** [comment]
@elit-altum I believe the last person to attempt to fix this also encountered the same issue. I'm not sure about changing the workflow, @DianaLease or @irmerk would know more about this.

**Comment by jolanglinais** [comment]
If this is still an issue, it will be resolved in `cicero-ui`. Closing this issue.
