### ISSUE TITLE
Font Changes in List

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#153]
**Describe the bug**
Changing a text block to a list removes font attributes.

**To Reproduce**
1. Go to [TSv2](https://accordproject-studio.netlify.com/)
2. Open the developer tools (Chrome on Mac is `CMD+OPTION J`)
3. Note that the font of the current text is `Graphik`
4. Select text, click on bulleted list
5. Note the font has changed and it is now listed as `serif`

**Expected behavior**
Font styling should persist in list form

**Screenshots**
Before:
<img width="1680" alt="Screen Shot 2019-08-28 at 10 17 47 AM" src="https://user-images.githubusercontent.com/36460856/63864319-a05c2880-c97d-11e9-862c-4ae63f342cd2.png">
After:
<img width="1680" alt="Screen Shot 2019-08-28 at 10 18 58 AM" src="https://user-images.githubusercontent.com/36460856/63864335-a7833680-c97d-11e9-932f-13da2d45642e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome and Safari

**Additional context**
N/A

**Comment by jolanglinais** [comment]
All that needs to be done is updating this line to include `li`, `ol`, and `ul`:

https://github.com/accordproject/template-studio-v2/blob/master/src/index.css#L36

**Comment by sachdeva-shrey** [comment]
I am not able to reproduce this issue. I think this has already been solved. @irmerk 
Can we close this issue?

**Comment by jolanglinais** [comment]
Yes I believe so.
