### ISSUE TITLE
Start from CTA file option on welcome screen

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/template-studio-v2#158]
As a user I would like to be able to start a contract/clause template from an existing CTA file I have on my computer. 

Potential scenario: a developer is working on the CTA file in the terminal or VSCode and sends the file to a lawyer to edit the legal text. The lawyer opens Template Studio and sees the welcome screen with an inviting prompt to start a contract from a CTA file. They lawyer drags the CTA file onto the welcome screen and drops it into the upload area, which opens the contents of the CTA file in Template Studio.

https://github.com/accordproject/template-studio-v2/issues/116

Add a section to the welcome screen called "Start from .cta file". See following invision mockup:
https://invis.io/9GRP1QB8D2U#/394150356_Welcome_1c
![image](https://user-images.githubusercontent.com/40569793/69168476-bf71de80-0ac4-11ea-9c1a-de6ec5ca8d39.png)

When the user drags a file onto the screen, show this dotted area that the user can drop their file into:
![image](https://user-images.githubusercontent.com/40569793/69183242-a70fbd00-0ae0-11ea-9b62-22472e69fe78.png)
https://invis.io/9GRP1QB8D2U#/394188621_Welcome_1c_Drag

If the file is not a valid .cta file, show an error message using semantic UI saying that the file is not valid.

use the inspect tool in the lower right to view the CSS of the prototype. You may need to request permission to view.

For the white button with green stroke, reference the white buttons on the Accord Project homepage:
https://www.accordproject.org/
![image](https://user-images.githubusercontent.com/40569793/69160014-d01b5800-0ab6-11ea-8b4f-f0eea059e89f.png)

Reference this issue and PR for the original welcome screen:
https://github.com/accordproject/template-studio-v2/issues/116
https://github.com/accordproject/template-studio-v2/pull/120

**Comment by Michael-Grover** [comment]
Added detail

**Comment by jeromesimeon** [comment]
I would love to have a way to "escape" from the welcome page. (e.g., a X on the top right, or if I press `escape` to be taken to the editor -- maybe with the empty contract as default).

**Comment by Michael-Grover** [comment]
What is the value of doing that? How would the user know what kind of template is opened by leaving the welcome page?

**Comment by sachdeva-shrey** [comment]
I think this issue has already been solved as I'm getting a welcome screen here or would you like the drag and drop feature to be added to this? @Michael-Grover 

![welcome](https://user-images.githubusercontent.com/47667325/75343146-d0996b00-58bd-11ea-96fb-36ef71535d6e.PNG)

**Comment by jolanglinais** [comment]
I believe we can close this issue for the time being.
