### ISSUE TITLE
Image Description Accessibility

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#38]
# WCAG 2.0 Level A [1.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html) (Non-text Content) 

## Tasks
- Use unique and descriptive `alt="..."` tags in images. Ensure all images used for decoration only contain an empty string for `alt`. Describe purpose or meaning of image, and include any text which exists in the image.

## Related Issues: 
- Issue [#53](https://github.com/accordproject/cicero-ui/issues/53) in Cicero-UI

**Comment by N7Layla** [comment]
Would love to potentially take this on, is there anything to be aware of first or would it just be a matter of going through to check images for alternate text and add where applicable?

**Comment by jolanglinais** [comment]
> Would love to potentially take this on, is there anything to be aware of first or would it just be a matter of going through to check images for alternate text and add where applicable?

I believe that would be the best approach, as far as I know.

**Comment by Sweta271097** [comment]
@irmerk Is this taken? Or can I work on it?

**Comment by jolanglinais** [comment]
I don't believe @N7Layla has done anything in the last week, so go for it.

**Comment by sachdeva-shrey** [comment]
I searched entire repo, it doesn't contain any images that don't have the `alt` attribute. I believe we can close this issue for now. @irmerk
