### ISSUE TITLE
Table Accessibility

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#39]
# WCAG 2.0 Level A [1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html) (Info and Relationships)

## Tasks
- Ensure `table` elements are accessible through proper usage of:
  -  `<thead>` and `<tbody>` for better navigation through a table
  - Column and Row header `<th>` elements need a scope attribute 
      - (`<th scope="col">` and `<th scope="row">`)
  - Tables should contain a `<caption>` (for the title) to help describe the `table`
      - Switch the header used prior to the `table` element with a caption element *inside* the `table`
      - Add a visually hidden description to the `<caption>`

## Related Issues: 
- Issue [#54](https://github.com/accordproject/cicero-ui/issues/54) in Cicero-UI

**Comment by nicoleCamoro** [comment]
hello, can I work on this?

**Comment by nicoleCamoro** [comment]
Thanks for assigning me to this. Just wanted to know if there is anything specific where I should look at. I tried looking around but didn't find any tables to enhance.

**Comment by jolanglinais** [comment]
@nicoleCamoro thee might actually not be any. I did a sweep through initially to create A11Y related issues on anything that I thought was possibly an issue, so this may be a non-issue. I can close it if you agree.

**Comment by nicoleCamoro** [comment]
@irmerk I agree so you can close this. If I find any other A11Y issues, would it be ok for me to submit and issue here and work on it? I'm using a tool so I know the possible things to tackle.

**Comment by jolanglinais** [comment]
> @irmerk I agree so you can close this. If I find any other A11Y issues, would it be ok for me to submit and issue here and work on it? I'm using a tool so I know the possible things to tackle.

If I understand you corrrectly, yes feel free to open A11Y issues (or any other) and work on them.
