### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/template-studio-v2#5]
It might be nice to have a welcome page in the template studio, maybe with the following options:
- Search template library
- New template (text only)
- New template (full)
- Drag and drop archive
- Load archive from URL

**Comment by Sweta271097** [comment]
@irmerk Are you looking for only the front-end of the welcome page?

**Comment by jolanglinais** [comment]
@Sweta271097 I'm unsure what you mean.

**Comment by archhhh** [comment]
hi, i am thinking about taking this one if you don't mind. one question is what should UI look like? should it be something similar to what is in accordproject.org?

**Comment by jolanglinais** [comment]
> hi, i am thinking about taking this one if you don't mind. one question is what should UI look like? should it be something similar to what is in accordproject.org?

I think @Michael-Grover would have the best input here.

**Comment by Michael-Grover** [comment]
I'll work on a design and post it here when it's ready

**Comment by jolanglinais** [comment]
Closed for #116
