### ISSUE TITLE
Contract Editor Scroll On Click

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#78]
**Describe the bug**

**To Reproduce**
1. Open [Template Studio v2](https://accordproject-studio.netlify.com/)
2. Create enough line breaks with `Enter` to have plenty of length to scroll
3. Add a clause (Acceptance of Delivery) to the bottom of the editor
4. Add a clause (Eat Apples) to the top of the editor
5. Scroll down, click inside the clause
6. Should cause a buggy scroll to top

**Expected behavior**
Clicking into a clause should not place the cursor outside of the clause

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome & Safari

**Additional context**
- This issue may be from deeper in the stack

**Comment by qualitymanifest** [comment]
I've also noticed that simply repeating steps 1 and 2, then clicking outside of the editor and clicking back into the editor will make it jump. Something weird going on with the focus?

Also just noticed that neither of what I describe can be replicated at https://www.slatejs.org so leaning toward some strange focus bug.

**Comment by qualitymanifest** [comment]
Turns out it's a slate error. The instructions in this comment fixes it https://github.com/ianstormtaylor/slate/issues/1551#issuecomment-465136126

I think I may have a solution that fixes it with just CSS, I'll submit a PR in the afternoon.

**Comment by qualitymanifest** [comment]
So right before I submitted a PR I noticed that [my css fix](https://github.com/qualitymanifest/markdown-editor/commit/2640a4694800cc150baae7766038b601c3af6c49) makes it so that the editor doesn't automatically scroll anymore when the cursor goes below the window, you have to scroll manually. [The Slate fix I mentioned before](https://github.com/ianstormtaylor/slate/issues/1551#issuecomment-465136126) does the same thing.

I've figured out how to fix both of these issues from within `slate-react.es.js`, but I'm trying to figure out the root cause as I think my fix is more of a band-aid. Might be next week before I can get around to it.

**Comment by jolanglinais** [comment]
Thanks so much for the follow up, @qualitymanifest 🙇

**Comment by jolanglinais** [comment]
@qualitymanifest I wanted to check in and see if I could be of any help on this, were you able to make any progress?

**Comment by qualitymanifest** [comment]
Sorry, I should have said something, I've been busy and had to prioritize other things. I found four potential ways of dealing with it but each have their own considerations:

1. [Commenting out the `scrollToSelection` call entirely](https://github.com/ianstormtaylor/slate/issues/1551#issuecomment-465136126)
2. Applying `overflow-y: scroll` to the element that [`findScrollContainer`](https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate-react/src/utils/scroll-to-selection.js#L25) returns
3. Adding `if (cursorRect.top < 0) { return; }` after [this line](https://github.com/ianstormtaylor/slate/blob/3dce916074e0294a5045f9c47f6932ac5841e947/packages/slate-react/src/utils/scroll-to-selection.js#L74) in scroll-to-selection.js
4. [Commenting out this line](https://github.com/ianstormtaylor/slate/blob/79a2d215713ee55f4f758eaecaa1a8189f804a26/packages/slate-react/src/plugins/dom/after.js#L404)

**1** and **2** get rid of the focus jumping, but disable the auto-scrolling of the editor when the cursor goes below or above the view by typing or using arrow keys

**3** and **4** get rid of focus jumping and allow the editor to keep scrolling normally with the cursor. I am unsure if these could introduce other bugs, but I didn't find any problems while i was trying it out.

All except for **2** require modifying the `slate-react` dependency, so I wasn't sure how you would want to go about that.

**Comment by jolanglinais** [comment]
No worries, this is all super helpful for whoever is able to pick up this issue next!
