### ISSUE TITLE
Offset Scroll To Clause

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#79]
**Describe the bug**
The `Toolbar` from `@accordproject/markdown-editor` hides the top of a clause when navigated through the `Navigation` component

**To Reproduce**
1. Open [Template Studio v2](https://accordproject-studio.netlify.com/)
2. Create enough line breaks with `Enter` to have plenty of length to scroll
3. Add a clause (Acceptance of Delivery) to the bottom of the editor
4. Add a clause (Eat Apples) to the top of the editor
5. Scroll down, click the heading of the top clause on the left Navigation
6. Should scroll to the clause, but the top of the clause will be hidden

**Expected behavior**
Navigating to a clause should be offset by the height of the `@accordproject/markdown-editor` `Toolbar`

**Screenshots**
<img width="969" alt="Screen Shot 2019-08-22 at 2 05 24 PM" src="https://user-images.githubusercontent.com/36460856/63538508-05c79980-c4e6-11e9-84cd-317037d92243.png">

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Chrome & Safari

**Additional context**
- Related to Issue #55

**Comment by DianaLease** [comment]
Fixed in https://github.com/accordproject/template-studio-v2/pull/104
