### ISSUE TITLE
Generate Errors as Objects

### ISSUE THREAD

**Issue by jolanglinais** [accordproject/template-studio-v2#86]
**Is your feature request related to a problem? Please describe.**
Revisit `contractReducer` logic and how we generate errors. Right now, the errors get added to an array every time a clause is parsed. This means if multiple changes cause a clause to be parsed multiple times, the same error will be added to the array multiple times and we end up with multiple of the same error.

**Describe the solution you'd like**
It makes more sense to use an object instead of an array, where the `clauseId` are keys and we update the error by `clauseId`, so we only ever have one error per clause.

**Describe alternatives you've considered**
Any alternatives are welcome.

**Additional context**
[Related issue in Cicero UI](https://github.com/accordproject/cicero-ui/issues/137)

**Comment by christyjacob4** [comment]
Can I work on this @irmerk

**Comment by christyjacob4** [comment]
Hey @irmerk  are the changes you requested to be in 
src/reducers/contractReducer.js

**Comment by Ph0tonic** [comment]
Hello,

I had a look at the code:

- https://github.com/accordproject/template-studio-v2/blob/master/src/reducers/contractReducer.js

But it seems to me that clauses are already stored inside an object. What else has to be done ?
Thanks

**Comment by jolanglinais** [comment]
@Ph0tonic yes the clauses are in an object, but the way in which we shape the errors to pass down to `cicero-ui` to be displayed in the `ErrorLogger` is here: https://github.com/accordproject/template-studio-v2/blob/master/src/containers/Error/errorReducer.js

**Comment by Ph0tonic** [comment]
Thanks @irmerk, so the errorReducer should return an object instead of an Array.
Can I work on this ?

**Comment by jolanglinais** [comment]
This specific issue is closed, but testing continues in Cicero UI #167
