### ISSUE TITLE
Difficult to find Netlify preview in Readme

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/template-studio-v2#94]
It is hard to find the Netlify preview of Template Studio V2 in the readme for people who don't know the Netlify badge is clickable and that it brings the user to a page where they can click a link to go to the preview.

**Comment by Michael-Grover** [comment]
https://accordproject-studio.netlify.com/

Please add this link below the Netlify badge in the readme

**Comment by Niladri24dutta** [comment]
@irmerk @Michael-Grover as the previous PR is closed, I have raised a similar PR to add the hyperlink for Template Studio V2 preview on Netlify. Please let me know if it can be merged.
